version: '3'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: kishore
      MYSQL_PASSWORD: kishore
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8080:80'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data: